"""
Enumeration types for the AML detection system
"""
from enum import Enum, auto


class AssetType(str, Enum):
    """Types of financial assets"""
    FIAT = "FIAT"
    CRYPTO = "CRYPTO"
    PRECIOUS_METALS = "PRECIOUS_METALS"
    REAL_ESTATE = "REAL_ESTATE"
    SECURITIES = "SECURITIES"
    COMMODITIES = "COMMODITIES"


class RiskLevel(str, Enum):
    """Risk level classifications"""
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TransactionStatus(str, Enum):
    """Transaction processing status"""
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    APPROVED = "APPROVED"
    FLAGGED = "FLAGGED"
    BLOCKED = "BLOCKED"
    INVESTIGATING = "INVESTIGATING"
    SAR_FILED = "SAR_FILED"


class AlertType(str, Enum):
    """Types of AML alerts"""
    STRUCTURING = "STRUCTURING"
    UNUSUAL_PATTERN = "UNUSUAL_PATTERN"
    HIGH_RISK_COUNTRY = "HIGH_RISK_COUNTRY"
    SANCTIONS_HIT = "SANCTIONS_HIT"
    PEP_DETECTED = "PEP_DETECTED"
    CRYPTO_MIXER = "CRYPTO_MIXER"
    TRADE_ANOMALY = "TRADE_ANOMALY"
    RAPID_MOVEMENT = "RAPID_MOVEMENT"
    SHELL_COMPANY = "SHELL_COMPANY"
    MISSING_DOCUMENTS = "MISSING_DOCUMENTS"
    INVOICE_MISMATCH = "INVOICE_MISMATCH"
    PROHIBITED_GOODS = "PROHIBITED_GOODS"
    DARKNET_CONNECTION = "DARKNET_CONNECTION"


class DocumentType(str, Enum):
    """Types of supporting documents"""
    INVOICE = "INVOICE"
    CONTRACT = "CONTRACT"
    SHIPPING_MANIFEST = "SHIPPING_MANIFEST"
    CUSTOMS_DECLARATION = "CUSTOMS_DECLARATION"
    BANK_STATEMENT = "BANK_STATEMENT"
    ID_DOCUMENT = "ID_DOCUMENT"
    COMPLIANCE_CERTIFICATE = "COMPLIANCE_CERTIFICATE"
    TRADE_AGREEMENT = "TRADE_AGREEMENT"
    BILL_OF_LADING = "BILL_OF_LADING"
    LETTER_OF_CREDIT = "LETTER_OF_CREDIT"


class CountryRiskLevel(str, Enum):
    """Country risk classifications"""
    LOW_RISK = "LOW_RISK"
    MEDIUM_RISK = "MEDIUM_RISK" 
    HIGH_RISK = "HIGH_RISK"
    TAX_HAVEN = "TAX_HAVEN"
    SANCTIONED = "SANCTIONED"
    EMBARGO = "EMBARGO"


class InvestigationStatus(str, Enum):
    """Investigation case status"""
    OPEN = "OPEN"
    IN_PROGRESS = "IN_PROGRESS"
    PENDING_REVIEW = "PENDING_REVIEW"
    ESCALATED = "ESCALATED"
    CLOSED_NO_ACTION = "CLOSED_NO_ACTION"
    CLOSED_SAR_FILED = "CLOSED_SAR_FILED"
    CLOSED_REFERRED = "CLOSED_REFERRED"


class AnalysisType(str, Enum):
    """Types of analysis performed"""
    TRANSACTION_SCREENING = "TRANSACTION_SCREENING"
    BEHAVIORAL_ANALYSIS = "BEHAVIORAL_ANALYSIS"
    GEOGRAPHIC_RISK = "GEOGRAPHIC_RISK"
    DOCUMENT_ANALYSIS = "DOCUMENT_ANALYSIS"
    SANCTIONS_SCREENING = "SANCTIONS_SCREENING"
    PEP_SCREENING = "PEP_SCREENING"
    ENHANCED_DUE_DILIGENCE = "ENHANCED_DUE_DILIGENCE"
    CRYPTO_ANALYSIS = "CRYPTO_ANALYSIS"
    NETWORK_ANALYSIS = "NETWORK_ANALYSIS"


class AgentRole(str, Enum):
    """Multi-agent system roles"""
    ORCHESTRATOR = "ORCHESTRATOR"
    RISK_ASSESSOR = "RISK_ASSESSOR"
    DOCUMENT_ANALYZER = "DOCUMENT_ANALYZER"
    BEHAVIOR_ANALYST = "BEHAVIOR_ANALYST"
    SANCTIONS_SCREENER = "SANCTIONS_SCREENER"
    CRYPTO_SPECIALIST = "CRYPTO_SPECIALIST"
    GEOGRAPHIC_ANALYST = "GEOGRAPHIC_ANALYST"
    COMPLIANCE_OFFICER = "COMPLIANCE_OFFICER"